const fs = require("fs");
const path = require("path");

const projectRoot = path.resolve(__dirname, "..");
const srcRoot = path.join(projectRoot, "src", "site");
const dataRoot = path.join(srcRoot, "data");
const pageRoot = path.join(srcRoot, "pages");
const partialRoot = path.join(srcRoot, "partials");
const layoutRoot = path.join(srcRoot, "layouts");
const styleRoot = path.join(projectRoot, "assets", "styles");

function read(filePath) {
  return fs.readFileSync(filePath, "utf8");
}

function write(filePath, content) {
  fs.writeFileSync(filePath, content.replace(/\r?\n/g, "\n"), "utf8");
}

function readJson(fileName) {
  return JSON.parse(read(path.join(dataRoot, fileName)));
}

function escapeHtml(value) {
  return String(value ?? "").replace(/[&<>"']/g, ch => ({
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#39;"
  }[ch]));
}

function resolveValue(context, key) {
  return key.split(".").reduce((acc, part) => (acc && acc[part] !== undefined ? acc[part] : ""), context);
}

function renderTemplate(template, context = {}, currentDir = srcRoot) {
  const withIncludes = template.replace(/\{%\s*include\s+"([^"]+)"\s*%\}/g, (_, includePath) => {
    const absolute = path.join(srcRoot, includePath);
    return renderTemplate(read(absolute), context, path.dirname(absolute));
  });

  return withIncludes
    .replace(/\{\{\{\s*([^}]+?)\s*\}\}\}/g, (_, key) => String(resolveValue(context, key.trim()) ?? ""))
    .replace(/\{\{\s*([^}]+?)\s*\}\}/g, (_, key) => escapeHtml(resolveValue(context, key.trim()) ?? ""));
}

function navLinksHtml(items, activeId) {
  return items.map(item => {
    const active = item.id === activeId ? "is-active" : "";
    const className = ["top-nav-link", active].filter(Boolean).join(" ");
    return `<a class="${className}" href="${escapeHtml(item.href)}">${escapeHtml(item.label)}</a>`;
  }).join("");
}

function moreLinksHtml(items) {
  return items.map(item => `
    <a class="more-link" href="${escapeHtml(item.href)}">
      <strong>${escapeHtml(item.label)}</strong>
      <span>${escapeHtml(item.description)}</span>
    </a>`).join("");
}

function bottomNavHtml(items, activeId) {
  return items.map(item => {
    const active = item.id === activeId ? "is-active" : "";
    const className = ["bottom-nav-link", active].filter(Boolean).join(" ");
    return `<a class="${className}" href="${escapeHtml(item.href)}">${escapeHtml(item.shortLabel || item.label)}</a>`;
  }).join("");
}

function scriptTags(files = []) {
  const shared = [
    "assets/dto-core.js",
    "assets/scripts/site.js"
  ];
  return [...shared, ...files].map(src => `<script src="${src}" defer></script>`).join("\n");
}

function cssBundle() {
  const files = [
    "tokens.css",
    "base.css",
    "layout.css",
    "components.css",
    "home.css",
    "market.css",
    "plan.css",
    "execute.css",
    "review.css",
    "login.css",
    "bot.css",
    "poly.css",
    "sim.css"
  ];

  const output = [
    "/* Generated by scripts/build-site.js. Edit assets/styles/* or src/site/*. */",
    ...files.map(file => read(path.join(styleRoot, file)))
  ].join("\n\n");

  write(path.join(projectRoot, "assets", "app.css"), output);
}

function buildCanonicalPages() {
  const navigation = readJson("navigation.json");
  const routes = readJson("routes.json");
  const base = read(path.join(layoutRoot, "base.njk"));

  routes.canonical.forEach(route => {
    const content = read(path.join(pageRoot, route.template));
    const html = renderTemplate(base, {
      title: route.title,
      description: route.description,
      pageId: route.id,
      topNav: renderTemplate(read(path.join(partialRoot, "top-nav.njk")), {
        primaryLinks: navLinksHtml(navigation.primary, route.id),
        moreLinks: moreLinksHtml(navigation.more)
      }),
      bottomNav: renderTemplate(read(path.join(partialRoot, "bottom-nav.njk")), {
        bottomLinks: bottomNavHtml(navigation.primary, route.id)
      }),
      footer: renderTemplate(read(path.join(partialRoot, "footer.njk")), {}),
      content,
      scripts: scriptTags(route.scripts || [])
    });
    write(path.join(projectRoot, route.file), html);
  });
}

function buildRedirectPages() {
  const routes = readJson("routes.json");
  const base = read(path.join(layoutRoot, "base.njk"));
  const redirectTemplate = read(path.join(pageRoot, "redirect.njk"));

  routes.redirects.forEach(route => {
    const content = renderTemplate(redirectTemplate, {
      redirectTarget: route.target,
      redirectHeadline: route.headline,
      redirectCopy: route.copy,
      redirectButton: route.buttonLabel || "Open current page"
    });

    const html = renderTemplate(base, {
      title: route.title,
      description: route.copy,
      pageId: "redirect",
      topNav: "",
      bottomNav: "",
      footer: "",
      content,
      scripts: `<script>window.__redirectTarget = ${JSON.stringify(route.target)};</script>\n<script src="assets/scripts/redirect.js" defer></script>`
    });

    write(path.join(projectRoot, route.file), html);
  });
}

function buildSite() {
  cssBundle();
  buildCanonicalPages();
  buildRedirectPages();
  return {
    canonicalCount: readJson("routes.json").canonical.length,
    redirectCount: readJson("routes.json").redirects.length
  };
}

if (require.main === module) {
  try {
    const result = buildSite();
    console.log(`[site-build] canonical pages: ${result.canonicalCount}`);
    console.log(`[site-build] redirect pages: ${result.redirectCount}`);
    console.log("[site-build] app.css regenerated");
  } catch (error) {
    console.error("[site-build] failed:", error.message);
    process.exit(1);
  }
}

module.exports = { buildSite };
